name: skola
description: A new Flutter project.



publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.3
  firebase_core: ^2.7.1
 
  firebase_database: ^10.0.15
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.5
  device_info_plus: ^9.0.2
  unique_identifier: ^0.3.0

flutter_intl:
  main_locale: hr
  enabled: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  freezed: ^2.3.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  custom_lint:
  riverpod_lint:

  
flutter: 
  uses-material-design: true

  fonts:
    - family: JosefinSans
      fonts:
        - asset: Assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: Assets/fonts/JosefinSans-Bold.ttf
          weight: 700
  assets:
    - Assets/images/