name: skola
description: A new Flutter project.



publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'







dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.3
  firebase_core: ^2.7.1
  firebase_database: ^10.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1


  
  
flutter: 
  uses-material-design: true

  fonts:
    - family: JosefinSans
      fonts:
        - asset: Assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: Assets/fonts/JosefinSans-Bold.ttf
          weight: 700

