// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuDNCSfSK7g1XEkMyMX8B-xizmZhZsvdU',
    appId: '1:847310509:web:5768ada6a053f7359b6024',
    messagingSenderId: '847310509',
    projectId: 'coco-learning',
    authDomain: 'coco-learning.firebaseapp.com',
    databaseURL: 'https://coco-learning-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coco-learning.appspot.com',
    measurementId: 'G-70K620CFE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwlceJ8LHI4Kith6M2Qt3eIDmy8BlrSc0',
    appId: '1:847310509:android:f7b1840d4021e49d9b6024',
    messagingSenderId: '847310509',
    projectId: 'coco-learning',
    databaseURL: 'https://coco-learning-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coco-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3JQp5ErGscWQs-PFCL7mDNnz-nm_USWw',
    appId: '1:847310509:ios:dc2e433a6e6cf1ac9b6024',
    messagingSenderId: '847310509',
    projectId: 'coco-learning',
    databaseURL: 'https://coco-learning-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coco-learning.appspot.com',
    iosClientId: '847310509-q4q0pv30ii7h87q4efc8khkq84206b0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.skola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3JQp5ErGscWQs-PFCL7mDNnz-nm_USWw',
    appId: '1:847310509:ios:dc2e433a6e6cf1ac9b6024',
    messagingSenderId: '847310509',
    projectId: 'coco-learning',
    databaseURL: 'https://coco-learning-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coco-learning.appspot.com',
    iosClientId: '847310509-q4q0pv30ii7h87q4efc8khkq84206b0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.skola',
  );
}
